### ISSUE TITLE
[Runtime Error] Cannot use manim-slides on WSL 2 with Ubuntu 20.04

### ISSUE THREAD

**Issue by rdheerajp** [jeertmans/manim-slides#106]
### Please explain the issue you're experiencing (with as much detail as possible):

Was excited to use manim-slides but unfortunately, there's a runtime error I can't figure out with manimpango library.

when I run the manim-slides command with a scene. the traceback points me to a manimpango import error.

``` 
ImportError:

ManimPango could not import and load the necessary shared libraries.
This error may occur when ManimPango and its dependencies are improperly set up.
Please make sure the following versions are what you expect:

    * ManimPango v0.4.2, Python v3.9.15

If you believe there is a greater problem,
feel free to contact us or create an issue on GitHub:

    * Discord: https://www.manim.community/discord/
    * GitHub: https://github.com/ManimCommunity/ManimPango/issues

Original error: manim-env/lib/libgobject-2.0.so.0: undefined symbol: g_uri_ref 

```

I have tried several versions of manimpango and I don't have any issues running manim and I can also generate the mp4 files for the slides.

Any help would be greatly appreciated.
TIA!

**Comment by jeertmans** [comment]
Hi @rdheerajp! Thank you for opening this issue.

In order to help you, I need to know a few things:

- Do you use Manim or ManimGL to render the scenes?
- Does scenes rendering work?
- Can you show the complete debug output (use verbose flag) of the command that does not work? On top of that, can you mention the exact command you used?

Aside of that, I am a bit curious: why are you using WSL, when easier installation processes exist directly on Windows. E.g., I have both Windows and Ubuntu, and on my Windows PC a simple `choco install` command was sufficient to install properly Manim and its dependencies.
