### ISSUE TITLE
Replay doesn't work after Reverse in Windows

### ISSUE THREAD

**Issue by arashash** [jeertmans/manim-slides#24]
So after Reversing a slide, the Replay key also Reverses! and the only way to make Replay work is to move back and forward the slide

**Comment by jeertmans** [comment]
Hi @arashash !

Yes, I know that the reverse mode is sometime counter-intuitive.
Currently, you can "replay" a slide that was previously reversed, but you need to press "next".

I agree that I need to enhance the "UI" documentation, and I might change the behavior so that rewind always replays the slide in the "normal" mode, never in reversed.

**Comment by jeertmans** [comment]
#28 should fix this issue ;-)

**Comment by arashash** [comment]
Awesome 😎
