### ISSUE TITLE
DOC: example does not match API

### ISSUE THREAD

**Issue by cogan-shimizu** [jeertmans/manim-slides#307]
### Describe the Issue

The `start_loop` and `end_loop` are still used in the example on the front page, but according to the [changelog](https://github.com/jeertmans/manim-slides/blob/main/CHANGELOG.md) for v5, this was a breaking change (#294). 

Definitely made for an interesting hiccup in starting out ;)

### Affected Page

https://www.manim.community/plugin/manim-slides/

### Issue Type

Documentation Enhancement

### Recommended fix or suggestions

```
        self.next_slide(loop=True)  # Waits user to press continue to go to the next slide

        self.play(MoveAlongPath(dot, circle), run_time=2, rate_func=linear)
        self.next_slide()
```
or something similar, not sure if that's the exact practice -- but it compiles and presents!

**Comment by jeertmans** [comment]
Hello @cogan-shimizu, thanks for reaching out!

Actually, this isn't a "Manim Slides" issues, but an issue from the Manim Community Plugin site that is not updated correctly.

The documentation from Manim Slides is up-to-date, see: https://github.com/jeertmans/manim-slides. In general, you should refer to this page and my website for the docs.

The page you linked is actually scraped from PyPI, but does not seem to be up-to-date.
Sadly, I cannot do anything about that, because I do not own Manim plugins :/
