### ISSUE TITLE
[FEATURE] Add key binding for previous-and-reverse slide

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#308]
### Description

As suggested by M. Pardo in an e-mail, it could be nice to have a (new) key binding that play the previous slide in reverse. This way, you can go through each slide in reverse until the start of the presentation.

A question I still have: should the current slide be played on the first press?

**Comment by Mapaor4** [comment]
I'm not sure about the implementation, but I think that ideally it would be great to have 3 different key bindings for going to the previous slide.

1. Reverse to the end of the previous slide

2. Go directly to the end of the previous slide

3. Go directly to the beginning of the previous slide

(One being the current reverse modified, the second one being an extra key binding which would have to be implemented, and the third one being the current left arrow as it is).

I've edited a little video (attached) to try to show what I'm referring to visually.

So this GitHub issue should be about option number 1. Currently there is the V key binding that plays the reverse animation, but it cannot be pressed twice or it produces a visual error. So making it not only reverse but also go to the end of the previous slide would allow for a continuous back and forth between slides.

PS: About the first slide, I guess in the ideal case if the button is pressed it should play the reverse animation, but otherwise it is probably simpler to just not play anything at all, which is also fine.

https://github.com/jeertmans/manim-slides/assets/57571130/635309a6-6410-47a2-b77e-ac1b4c60b8be

**Comment by jeertmans** [comment]
Thanks for commenting @Mapaor4! I will take a deeper look at this when I have some time :-)

If anyone wants to give it a try, please do!
