### ISSUE TITLE
Import video and sound to manim-slides

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides#379]
### use *self.add("sound.mp3")* to add a sound in anywhere of the manim-slides

Thx a lot!

**Comment by jeertmans** [comment]
Hello! The features you are asking for are not 

# Adding a video file

Manim does not allow to easily load a video from a file. I have myself made a PR to add some basic `VideoMobject` class to Manim (https://github.com/ManimCommunity/manim/pull/3496), but this is still work in progress due to https://github.com/ManimCommunity/manim/pull/3501.

In the meantime, you can implement a basic `VideoMobject` by copying/pasting the code from https://github.com/ManimCommunity/manim/pull/3496/files.

# Adding a sound file

Currently, you can add audio files in Manim with `self.add("audio.mp4")`, but the sound will not be played in Manim Slides. This is because Manim does not add the audio soundtrack to partial video files, which are used by Manim Slides to create the different slides.

This issue is tracked by #375.
