### ISSUE TITLE
[FEATURE] Interactive Feature with Mouse and Keyboard

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides#380]
### Description

- use **mobject.on_mouse_motion(scale(2))** to make the mobject scale 2 times when mouse hover on the mobject, make it interactive.
- use **self.on_keyboard_press("R",self.play(Creation(circle))** to create a circle after pressing the key "R"
-  use **icon = Icon(self.play(Creation(circle))**  to make an interactive icon: afetr press the icon, the corresponding animation will be played.
Thx a lot!

**Comment by jeertmans** [comment]
Hello! The interactive features you are suggesting cannot be integrated with Manim Slides, sadly.

This is because Manim Slides uses nothing but rendered videos to generated (static) slides.
The `Mobject.on_mouse_motion` and related methods are available only if (and while) you use the OpenGL renderer Windows with Manim.

If you want to have such interactivity, I am afraid that the best is maybe just to stuck to Manim and the OpenGL live preview renderer.

**Comment by jeertmans** [comment]
Closing this issue as this is not part of this project's scope.
