### ISSUE TITLE
[BUG] Installation fails when collecting `rtoml>=0.9.0`

### ISSUE THREAD

**Issue by 1Dung** [jeertmans/manim-slides#398]
### Please explain the issue you're experiencing (with as much detail as possible):

Today I installed manim slides for a friend, with python version 3.11.8. I tried to install using pip: "pip install manim-slides". And I get the following error. I searched a lot for information but couldn't find a solution. How to fix that?
![issue](https://github.com/jeertmans/manim-slides/assets/165900107/b332cfaa-5698-4555-83f4-a9a32bf0da35)

**Comment by jeertmans** [comment]
Hello, thanks for posting the issue here!

The problem seems to come from `rtoml`, which should ship pre-built binary wheels for most platforms (including Windows). But it looks like it is not able to find such pre-built wheels, and thus it tries to build (hence the Rust compilation) them locally, and fails because you do not have Rust installed.

Can you confirm that this is the problem by trying: `pip install rtoml==0.10.0`?

Also, can you provide more information about your [Windows version](https://support.microsoft.com/en-us/windows/which-version-of-windows-operating-system-am-i-running-628bec99-476a-2c13-5296-9dd081cdd808#:~:text=in%20Windows%2010-,To%20find%20out%20which%20version%20of%20Windows%20your%20device%20is,%3E%20Settings%20%3E%20System%20%3E%20About%20.)?

**Comment by 1Dung** [comment]
Thank you for responding.
I tried to run: `pip install rtoml==0.10.0` but this is the result I got.
I am using window11.
![Uploading issue2.jpg…]()

**Comment by jeertmans** [comment]
The picture does not load: did you correctly upload it?

**Comment by 1Dung** [comment]
Yes, I re-uploaded it. It's too late now, I'll respond to your help tomorrow. Thank you very much.

**Comment by jeertmans** [comment]
Thanks, but was asking for the specific windows version (which you can obtain as described in the link above) :-)

**Comment by 1Dung** [comment]
Yes, this is the version of windows in use.
![window_ver](https://github.com/jeertmans/manim-slides/assets/165900107/6be05586-3b76-45a3-97d9-859bb9c006af)

**Comment by jeertmans** [comment]
Ok so this looks like this is a known issue, see https://github.com/samuelcolvin/rtoml/issues/74.

A solution might be to `pip install rtoml==0.9.0`. Then, `pip install manim-slides` should work. Can you try?

**Comment by 1Dung** [comment]
Ok, I will try. I will respond to the results here. Thank you.

**Comment by jeertmans** [comment]
Thank you for updating @1Dung :-)
