### ISSUE TITLE
[FEATURE] Force re-render in manim-slides

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides#408]
### Please explain the issue you're experiencing (with as much detail as possible):

Hi, there. I found that sometimes I just change the **background color** in the front of my code and want to render it again.
```py
config.background_color = BLACK
# config.background_color = WHITE  # 
```
However, the manim-slides will simply use the **cached files** and won't render again, unless I deleted every file it will re render again. Is there anyway else to force render a class again? Thx a lot~:)

**Comment by jeertmans** [comment]
Hello!

Is it Manim Slides that skips re-rendering (because we re-use cached file for concatenated and reversed files), or is it Manim (it also uses cached files, based on a `hash` function, that I guess does not rely on `config` :-/).

In the latter case, you can use `manim-slides render slide.py Slide --disable_caching`.

Regarding Manim Slides, there is a class option, but this does not read from the CLI at the moment. I should somehow check if the `--disable_caching` option was passed and use it.
