### ISSUE TITLE
[Help] Low resolution/Blurred image on MacOS Ventura

### ISSUE THREAD

**Issue by algasami** [jeertmans/manim-slides#81]
### Please explain the issue you're experiencing (with as much detail as possible):

I've tried to debug this issue with the solution to #20 , but it didn't seem to work.
Here's a screenshot of what happened:
https://imgur.com/a/egBPG9E

Commands Used:
```
manimgl --uhd start.py
manim-slides Test
```
By the way, my Mac has the default scaling 😄

**Comment by jeertmans** [comment]
Hi @algasami, thank you for raising this issue ;-)

Would you mind taking a fullscreen screenshot of:

1. the video generated with `manimgl`, opened with any video player (in fullscreen),
2. and the video played by `manim-slides`, using `manim-slides Test --fullscreen`,

and put the images here?

That's to help with the comparison.

Thanks!

**Comment by algasami** [comment]
Alright 👍
This is the video's capture (appears to be UHD): https://imgur.com/Ni51CSS
And this is the slide's capture: https://imgur.com/2BADDph

**Comment by jeertmans** [comment]
I cannot see much difference, especially since the above video seems to be stretched. And I cannot reproduce this on Ubuntu (I don't have access to a macOS platform right now).

Can you try:
* using `--aspect-ratio=keep`;
* using a resolution that matches your screen resolution;
* or comparing `manimgl -r 1280x720 start.py` with `manim-slides Test --resolution 1280 720`?

If that does not solve your problem, can you post the code of `start.py` here?

**Comment by algasami** [comment]
I compared the 1280x720 slide with the video. Here's the screenshot: https://imgur.com/gGR39vi
The left one is the slide and the right one is the video. The circle in the video seems to be smoother than the one in the slide. (You need to zoom in to see the subtle effect, though.)

**Comment by algasami** [comment]
```py
from manimlib import *
from manim_slides import Slide

class Test(Slide):
    def construct(self):
        intro = Text("""
        test anti-aliasing
        """)
        intro.to_edge(UP)
        self.play(Write(intro))
        circle = Circle()
        circle.set_fill(BLUE_E, opacity=0.5)
        circle.set_stroke(BLUE_E, width=4)
        square = Square()

        self.play(ShowCreation(square))
        self.pause()
        self.play(ReplacementTransform(square, circle))
        self.wait()
```
start.py

**Comment by jeertmans** [comment]
Ok @algasami, I have a good new and a bad news: the good one is that I managed to reproduce your error, on macOS Ventura. The bad one is that I know need more investigation, since I currently do not know why the scaling looks so bad.

I need to:
- check if this problem only occurs on macOS;
- check if the problem comes from bad scaling, or from reading the file;
- and find how to fix this :'-)

For archive purposes, here are the comparison screenshots I took:
1. Using `1280x7201 resolution, and not scaling
  1.1 Opened with QuickTime player
  1.2 Opened with Manim Slides, using smooth scaling
  1.3 Opened with Manim Slides, using fast scaling
2. Using `--uhd` flag, and scaling to full screen (that's where I spot the differences) 
  2.1 Opened with QuickTime player
  2.2 Opened with Manim Slides, using smooth scaling
  2.3 Opened with Manim Slides, using fast scaling

When default scaling mode, i.e., smooth, the difference is subtle, but I understand that can be annoying.

<img width="1392" alt="hd-quicktime" src="https://user-images.githubusercontent.com/27275099/205451357-96d38e17-268b-43f6-ac55-4635495930fa.png">
<img width="1392" alt="hd-smooth" src="https://user-images.githubusercontent.com/27275099/205451359-68eced9d-04d4-4e20-84d8-d2f035df01de.png">
<img width="1392" alt="hd-fast" src="https://user-images.githubusercontent.com/27275099/205451363-79027958-3d59-463c-887b-a23a6982bd28.png">
<img width="2560" alt="uhd-fullscreen-quicktime" src="https://user-images.githubusercontent.com/27275099/205451373-a2361388-2d19-4973-bc28-9d3cc261c2ca.png">
<img width="2560" alt="uhd-fullscreen-smooth" src="https://user-images.githubusercontent.com/27275099/205451385-fe1aff20-61cc-4b4e-9ff3-dc5a226fe7cd.png">
<img width="2560" alt="uhd-fullscreen-fast" src="https://user-images.githubusercontent.com/27275099/205451389-5077002d-2c27-49c0-b649-1fc85ba72c51.png">

**Comment by algasami** [comment]
Thank you! I will try to find a workaround with this plugin meanwhile👍

**Comment by jeertmans** [comment]
Thanks! If you manage to find anything interesting, please feel free to share here so that we can improve this tool :)
